http:
  routers:
    blood-web:
      rule: "PathPrefix(`/blood-crypt`) || PathPrefix(`/leaderboard`) || PathPrefix(`/room`)"
      service: blood-web
      priority: 50
    blood-api:
      rule: "PathPrefix(`/api`)"
      service: blood-api
    portal:
      rule: "PathPrefix(`/`)"
      service: portal
      priority: 1

  services:
    blood-web:
      loadBalancer:
        servers:
          - url: "http://blood-web:80"
    blood-api:
      loadBalancer:
        servers:
          - url: "http://blood-api:3000"
    portal:
      loadBalancer:
        servers:
          - url: "http://portal:80"
